const assert=require('node:assert/strict');
const M=require('../web/track-model.js');
const observation=(id,ts,cell='ABC',rsrp=-90)=>({id,ts,gps_ts:ts,lat:52+id*.00001,lon:13,acc_m:5,gps_delta_s:0,radio:{lte_plmn:'262-01',lte_cell_id:cell,lte_band:'B3',lte_pci:10,lte_rsrp:rsrp,lte_sinr:15,lte_rsrq:-9,lte_bw:20}});
const points=[...Array(6)].map((_,i)=>observation(i,i));
let samples=M.samples(points);assert.equal(samples[3].stability,null);assert.equal(samples[4].stability,0);assert.equal(samples.filter(s=>s.change).length,0);
points.push(observation(6,6,'DEF'));points.push(observation(7,7,'ABC'));points.push(observation(8,20,'ABC'));
samples=M.samples(points);assert.equal(samples[6].change,true);assert.equal(samples[7].change,true);assert.equal(samples[7].stability,null);assert.equal(samples[8].change,false);assert.notEqual(samples[8].segment,samples[7].segment);assert.equal(samples[8].distance,samples[7].distance);
assert.equal(M.key({nr_plmn:'262-01',nr_band:'n78',nr_arfcn:640000,nr_pci:12},'nr'),null);
assert.equal(M.key({nr_plmn:'262-01',nr_cell_id:'00abc'},'nr'),'nr:262-01:ABC');
const unknown=[observation(20,30),observation(21,31)].map(o=>({...o,radio:{...o.radio,lte_cell_id:null}}));
const u=M.samples(unknown);assert.notEqual(u[0].identity,u[1].identity);assert.equal(u[1].change,false);assert.equal(u[1].stability,null);
assert.equal(M.color({rsrq:null},'rsrq'),'#9ba59e');assert.equal(M.color({stability:0},'stability'),'#21836b');
console.log('PASS: same-cell stability, minimum samples, handovers, gap segmentation, distance gaps, identity matching and unknown values');
